!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitrandom_module(f2pysetupfunc)
      use random_module, only : random_int
      use random_module, only : random_real
      use random_module, only : init_random_seed
      external f2pysetupfunc
      call f2pysetupfunc(random_int,random_real,init_random_seed)
      end subroutine f2pyinitrandom_module

      subroutine f2pywrap_list_generator_module_random_list (list, f2py_&
     &list_d0)
      use list_generator_module, only : random_list
      integer f2py_list_d0
      real list(f2py_list_d0)
      call random_list(list)
      end subroutine f2pywrap_list_generator_module_random_list
      
      subroutine f2pyinitlist_generator_module(f2pysetupfunc)
      interface 
      subroutine f2pywrap_list_generator_module_random_list (list, f2py_&
     &list_d0)
      integer f2py_list_d0
      real list(f2py_list_d0)
      end subroutine f2pywrap_list_generator_module_random_list
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_list_generator_module_random_list)
      end subroutine f2pyinitlist_generator_module


